config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :users
  resources :cursos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/controllers/bookmarks_controller.rb
require 'rest-client'

class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]
  # BASE_URL = 'https://canvas.docker.com/api/v1/users/self/bookmarks'
  # ACCESS_TOKEN = '7~Yb6tXYHm8k14eReNze0aY4mjZLDrr16GBPTRUuMe03rU7HbmTGSVETGcYhxKc13i'
  # ACCESS_TOKEN = 'vxg8lzP7auWExUH99JtPHr3PpSK2cghfCnx2xbFNVs6PJ30wn7YzO8Q3esPrTj9N'
  # GET /bookmarks or /bookmarks.json
  def index
    @bookmarks = Bookmark.all
    # response = RestClient.get("#{BASE_URL}?access_token=#{ACCESS_TOKEN}")
    # @bookmarks = JSON.parse(response.body)
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
    bookmark_id = params[:id]
    # response = RestClient.get("#{BASE_URL}/#{bookmark_id}?access_token=#{ACCESS_TOKEN}")
    # @bookmark = JSON.parse(response.body)
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to bookmark_url(@bookmark), notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end

    # Petición POST para crear un nuevo marcador (reemplaza bookmark_params con tus datos)
    # headers = {
    #   Authorization: "Bearer #{ACCESS_TOKEN}"
    # }

    # response = RestClient.post("#{BASE_URL}?access_token=#{ACCESS_TOKEN}", @bookmark, headers: headers)

    # response = RestClient.post("#{BASE_URL}?access_token=#{ACCESS_TOKEN}", bookmark_params)
    # @bookmark = JSON.parse(response.body)
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to bookmark_url(@bookmark), notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end

    # Petición PUT/PATCH para actualizar un marcador existente (reemplaza {bookmark_id} y bookmark_params)
    bookmark_id = params[:id]
    # response = RestClient.put("#{BASE_URL}/#{bookmark_id}?access_token=#{ACCESS_TOKEN}", bookmark_params)
    # @bookmark = JSON.parse(response.body)
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy!

    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end

    # Petición DELETE para eliminar un marcador existente (reemplaza {bookmark_id})
    bookmark_id = params[:id]
    # response = RestClient.delete("#{BASE_URL}/#{bookmark_id}?access_token=#{ACCESS_TOKEN}")
    # Maneja la respuesta según tus necesidades
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:name, :url, :position, :data)
    end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bookmark.html.erb
<div id="<%= dom_id bookmark %>">
  <p>
    <strong>Name:</strong>
    <%= bookmark.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= bookmark.url %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= bookmark.position %>
  </p>

  <p>
    <strong>Data:</strong>
    <%= bookmark.data %>
  </p>

</div>

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark) do |form| %>
  <% if bookmark.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.text_field :position %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.text_field :data %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render "form", bookmark: @bookmark %>

<br>

<div>
  <%= link_to "Show this bookmark", @bookmark %> |
  <%= link_to "Back to bookmarks", bookmarks_path %>
</div>

app/views/bookmarks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Bookmarks</h1>
<%= link_to "New bookmark", new_bookmark_path %>

<table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>URL</th>
        <th>Position</th>
        <th>Data</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @bookmarks.each do |bookmark|%>
      <tr>
        <td><%= bookmark.name %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.position %></td>
        <td><%= bookmark.data %></td>
        <td><%= link_to "Show this bookmark", bookmark %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render "form", bookmark: @bookmark %>

<br>

<div>
  <%= link_to "Back to bookmarks", bookmarks_path %>
</div>

app/views/bookmarks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bookmark %>

<div>
  <%= link_to "Edit this bookmark", edit_bookmark_path(@bookmark) %> |
  <%= link_to "Back to bookmarks", bookmarks_path %>

  <%= button_to "Destroy this bookmark", @bookmark, method: :delete %>
</div>