config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  resources :users
  resources :cursos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/curso.rb
class Curso < ApplicationRecord
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
    #Mostrar en el inicio
    # def index
    #     # @curso = Curso.all
    #     # p @curso.length #print
    #     # @courses = CanvasService.fetch_courses
    # end

    BASE_URL = 'https://canvas.instructure.com/api/v1/courses'
  ACCESS_TOKEN = '7~Yb6tXYHm8k14eReNze0aY4mjZLDrr16GBPTRUuMe03rU7HbmTGSVETGcYhxKc13i'

  def index
    # Petición GET para obtener la lista de cursos
    response = RestClient.get("#{BASE_URL}?access_token=#{ACCESS_TOKEN}")
    @courses = JSON.parse(response.body)
  end

  def show
    # Petición GET para obtener detalles de un curso específico (reemplaza {course_id} con el ID del curso)
    course_id = params[:id]
    response = RestClient.get("#{BASE_URL}/#{course_id}?access_token=#{ACCESS_TOKEN}")
    @course = JSON.parse(response.body)
  end

  def create
    # Petición POST para crear un nuevo curso (reemplaza course_params con tus datos)
    response = RestClient.post("#{BASE_URL}?access_token=#{ACCESS_TOKEN}", course_params)
    @course = JSON.parse(response.body)
  end

  def update
    # Petición PUT/PATCH para actualizar un curso existente (reemplaza {course_id} y course_params)
    course_id = params[:id]
    response = RestClient.put("#{BASE_URL}/#{course_id}?access_token=#{ACCESS_TOKEN}", course_params)
    @course = JSON.parse(response.body)
  end

  def destroy
    # Petición DELETE para eliminar un curso existente (reemplaza {course_id})
    course_id = params[:id]
    response = RestClient.delete("#{BASE_URL}/#{course_id}?access_token=#{ACCESS_TOKEN}")
    # Maneja la respuesta según tus necesidades
  end

  private

  def course_params
    # Define los parámetros necesarios para crear o actualizar un curso
    params.require(:course).permit(:name, :description, :other_attributes).to_json
  end

    # #llamar al formulario
    # def new
    #     @curso = Curso.new

    # end

    # #crear instancia
    # def create
    #     @curso = Curso.new(curso_params)
    #     if @curso.save
    #         redirect_to cursos_path
    #     else
    #         redirect_to new_curso_path
    #     end
    # end

    # def edit
    #     @curso = Curso.find(params[:id])
    # end

    # def update
    #     @curso = Curso.find(params[:id])

    #     if @curso.update(curso_params)
    #         redirect_to cursos_path
    #     else
    #         render :edit
    #     end
    # end

    # def destroy
    #     @curso = Curso.find(params[:id])
    #     @curso.destroy
    #     redirect_to cursos_path
    # end

    # private
    # def curso_params
    #     params.require(:curso).permit(:id_curso, :uuid, :nombre, :codigo, :nestudiantes)
    # end

    
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/edit.html.erb
<h1> edit </h1>

<%= form_for @curso do |f| %>
<div>
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
</div>
<div>
    <%= f.label :id_curso %>
    <%= f.text_field :id_curso %>
</div>
<div>
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
</div>
<div>
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
</div>
<div>
    <%= f.label :nestudiantes %>
    <%= f.text_field :nestudiantes %>
</div>
<div>
    <%= f.submit %>
    </div>

<% end %>

app/views/cursos/index.html.erb
<h1>CURSOS</h1>
<%= link_to "nuevo", new_curso_path %>
<table>
    <thead>
      <tr>
        <th>ID Curso</th>
        <th>Unique ID</th>
        <th>Nombre</th>
        <th>Codigo</th>
        <th>Numero de Estudiantes</th>
      </tr>
    </thead>
    <tbody>
    <% @curso.each do |data|%>
      <tr>
        <td><%= data.id_curso %></td>
        <td><%= data.uuid %></td>
        <td><%= data.nombre %></td>
        <td><%= data.codigo %></td>
        <td><%= data.nestudiantes %></td>
        <td><%= link_to "editar", edit_curso_path(data) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/cursos/new.html.erb
<h1> NUEVO </h1>

<%= form_for @curso do |f| %>
<div>
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
</div>
<div>
    <%= f.label :id_curso %>
    <%= f.text_field :id_curso %>
</div>
<div>
    <%= f.label :uuid %>
    <%= f.text_field :uuid %>
</div>
<div>
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
</div>
<div>
    <%= f.label :nestudiantes %>
    <%= f.text_field :nestudiantes %>
</div>
<div>
    <%= f.submit %>
    </div>

<% end %>